changelog:
  exclude:
    labels:
      - skip-changelog
      - duplicate
      - invalid
      - question
      - wontfix
  categories:
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Maintenance
      labels:
        - chore
        - dependencies
        - ci
